package main

import (

	// "github.com/gdamore/tcell"
	"github.com/gdamore/tcell/v2"
)

var bgrStyle tcell.Style
var OrangeDrawStyle tcell.Style
var YellowDrawStyle tcell.Style

func InitColor() {
	// define all colors as drawing color
	// defStyle := tcell.StyleDefault.Background(tcell.ColorReset).Foreground(tcell.ColorReset)
	bgrStyle = tcell.StyleDefault.Foreground(tcell.ColorLightGray).Background(tcell.ColorLightGray)

	OrangeDrawStyle = tcell.StyleDefault.Foreground(tcell.ColorOrange).Background(tcell.ColorOrange)
	YellowDrawStyle = tcell.StyleDefault.Foreground(tcell.Color226).Background(tcell.Color226)
	// RedDrawStyle := tcell.StyleDefault.Foreground(tcell.ColorIndianRed).Background(tcell.ColorIndianRed)
	// BlackDrawStyle := tcell.StyleDefault.Foreground(tcell.ColorBlack).Background(tcell.ColorBlack)
	// WhiteDrawStyle := tcell.StyleDefault.Foreground(tcell.ColorWhite).Background(tcell.ColorWhite)
	// DarkGreenDrawStyle := tcell.StyleDefault.Foreground(tcell.ColorDarkGreen).Background(tcell.ColorDarkGreen)
	// GreenDrawStyle := tcell.StyleDefault.Foreground(tcell.ColorGreen).Background(tcell.ColorGreen)
	// DarkOliveGreenDrawStyle := tcell.StyleDefault.Foreground(tcell.ColorDarkOliveGreen).Background(tcell.ColorDarkOliveGreen)
	// PurpleDrawStyle := tcell.StyleDefault.Foreground(tcell.ColorMediumPurple).Background(tcell.ColorMediumPurple)
	// LightBlueDrawStyle := tcell.StyleDefault.Foreground(tcell.ColorDeepSkyBlue).Background(tcell.ColorDeepSkyBlue)
	// NeonYellowDrawStyle := tcell.StyleDefault.Foreground(tcell.Color227).Background(tcell.Color227)
	// BlueDrawStyle := tcell.StyleDefault.Foreground(tcell.Color21).Background(tcell.Color21)
	return
}

// type Stage struct {
// 	content []string
// }

// // var YellowCastle Stage

// // YellowCastle = Stage{
// // 	content: castles,
// // }

// all different kinds of stages
// castles := []stringg{
// 	"XXXXXXXXXXXXXXXX   XXX   XXX   XXX            XXX   XXX   XXX   XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX   XXX   XXX   XXX            XXX   XXX   XXX   XXXXXXXXXXXXXXXX",
// 	"XX           XXX   XXX   XXX   XXX            XXX   XXX   XXX   XXX           XX",
// 	"XX           XXX   XXX   XXX   XXX            XXX   XXX   XXX   XXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXX            XXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           XX",
// 	"XX                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXX   ####   XXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXX   ####   XXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXX   ####   XXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXX   ####   XXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXX   ####   XXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXX   ####   XXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXX   ####   XXXXXXXXXXXXXXX                  XX",
// 	"XX                  XXXXXXXXXXXXXXX   ####   XXXXXXXXXXXXXXX                  XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// bottomOpen := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// bottomLeftRightOpen := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// topOpen := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// topLeftRightOpen := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// bottomTopOpen := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XX                                                                            XX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// bottomTopLeftRightOpen := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// orangeTop := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"         XXX                                                        XXX         ",
// 	"         XXX                                                        XXX         ",
// 	"         XXX                                                        XXX         ",
// 	"         XXX                                                        XXX         ",
// 	"         XXX                                                        XXX         ",
// 	"         XXX                                                        XXX         ",
// 	"         XXX                                                        XXX         ",
// 	"         XXX                                                        XXX         ",
// 	"XXXXX    XXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXX    XXXXX",
// 	"XXXXX    XXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXX    XXXXX",
// 	"XXXXX    XXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXX    XXXXX",
// 	"XXXXX    XXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXX    XXXXX",
// 	"XXXXX    XXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXX    XXXXX",
// 	"XXXXX    XXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXX    XXXXX",
// 	"XXXXX    XXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXX    XXXXX",
// 	"XXXXX    XXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXX    XXXXX",
// 	"XXXXX    XXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXX    XXXXX",
// 	"XXXXX    XXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXX    XXXXX",
// 	"         XXX                        XXXXXXXX                        XXX         ",
// 	"         XXX                        XXXXXXXX                        XXX         ",
// 	"         XXX                        XXXXXXXX                        XXX         ",
// 	"         XXX                        XXXXXXXX                        XXX         ",
// 	"         XXX                        XXXXXXXX                        XXX         ",
// 	"         XXX                        XXXXXXXX                        XXX         ",
// 	"         XXX                        XXXXXXXX                        XXX         ",
// 	"         XXX                        XXXXXXXX                        XXX         ",
// 	"XXXXXXXXXXXX    XXXX                XXXXXXXX                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX                XXXXXXXX                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX                XXXXXXXX                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX                XXXXXXXX                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX                XXXXXXXX                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX                XXXXXXXX                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX                XXXXXXXX                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX                XXXXXXXX                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX                XXXXXXXX                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX                XXXXXXXX                XXXX    XXXXXXXXXXXX",
// 	"                XXXX                XXXXXXXX                XXXX                ",
// 	"                XXXX                XXXXXXXX                XXXX                ",
// 	"                XXXX                XXXXXXXX                XXXX                ",
// 	"                XXXX                XXXXXXXX                XXXX                ",
// 	"                XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX                ",
// 	"                XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX                ",
// 	"                XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX                ",
// 	"                XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX                ",
// 	"XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX",
// }

// orangeMiddle := []string{
// 	"XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX",
// 	"                        XXXXXXXX    XXXXXXXX    XXXXXXXX                        ",
// 	"                        XXXXXXXX    XXXXXXXX    XXXXXXXX                        ",
// 	"                        XXXXXXXX    XXXXXXXX    XXXXXXXX                        ",
// 	"                        XXXXXXXX    XXXXXXXX    XXXXXXXX                        ",
// 	"                        XXXXXXXX    XXXXXXXX    XXXXXXXX                        ",
// 	"                        XXXXXXXX    XXXXXXXX    XXXXXXXX                        ",
// 	"                        XXXXXXXX    XXXXXXXX    XXXXXXXX                        ",
// 	"                        XXXXXXXX    XXXXXXXX    XXXXXXXX                        ",
// 	"XXX             XXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXX             XXX",
// 	"XXX             XXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXX             XXX",
// 	"XXX             XXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXX             XXX",
// 	"XXX             XXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXX             XXX",
// 	"XXX             XXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXX             XXX",
// 	"XXX             XXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXX             XXX",
// 	"XXX             XXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXX             XXX",
// 	"XXX             XXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXX             XXX",
// 	"XXX             XXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXX             XXX",
// 	"XXX             XXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXX             XXX",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"        XXXX    XXXX    XXXXXXXX                XXXXXXXX    XXXX    XXXX        ",
// 	"        XXXX    XXXX    XXXXXXXX                XXXXXXXX    XXXX    XXXX        ",
// 	"        XXXX    XXXX    XXXXXXXX                XXXXXXXX    XXXX    XXXX        ",
// 	"        XXXX    XXXX    XXXXXXXX                XXXXXXXX    XXXX    XXXX        ",
// 	"        XXXX    XXXX    XXXXXXXX                XXXXXXXX    XXXX    XXXX        ",
// 	"        XXXX    XXXX    XXXXXXXX                XXXXXXXX    XXXX    XXXX        ",
// 	"        XXXX    XXXX    XXXXXXXX                XXXXXXXX    XXXX    XXXX        ",
// 	"        XXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXX        ",
// 	"XXXX    XXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXX    XXXX",
// 	"XXXX    XXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXX    XXXX",
// }

// orangeBottom := []string{
// 	"XXXX    XXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXX    XXXX",
// 	"XXXX    XXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXX    XXXX",
// 	"        XXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXX        ",
// 	"        XXXX            XXXXXXXX    XXXXXXXX    XXXXXXXX            XXXX        ",
// 	"        XXXX            XXXXXXXX    XXXXXXXX    XXXXXXXX            XXXX        ",
// 	"        XXXX            XXXXXXXX    XXXXXXXX    XXXXXXXX            XXXX        ",
// 	"        XXXX            XXXXXXXX    XXXXXXXX    XXXXXXXX            XXXX        ",
// 	"        XXXX            XXXXXXXX    XXXXXXXX    XXXXXXXX            XXXX        ",
// 	"        XXXX            XXXXXXXX    XXXXXXXX    XXXXXXXX            XXXX        ",
// 	"        XXXX            XXXXXXXX    XXXXXXXX    XXXXXXXX            XXXX        ",
// 	"        XXXX            XXXXXXXX    XXXXXXXX    XXXXXXXX            XXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXX        ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"        XXXXXXXXXXXXXXXXXXX         XXXXXXXX         XXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXX         XXXXXXXX         XXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXX         XXXXXXXX         XXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXX         XXXXXXXX         XXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXX         XXXXXXXX         XXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXX         XXXXXXXX         XXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXX         XXXXXXXX         XXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXXXXXXXXXXXXXXXXX         XXXXXXXX         XXXXXXXXXXXXXXXXXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"        XXXX                        XXXXXXXX                        XXXX        ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
//	}

// redRightTop := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"                                    XXXXXXXX                                    ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                        XXXX        XXXXXXXX        XXXX                        ",
// 	"                        XXXX        XXXXXXXX        XXXX                        ",
// 	"                        XXXX        XXXXXXXX        XXXX                        ",
// 	"                        XXXX        XXXXXXXX        XXXX                        ",
// 	"                        XXXX        XXXXXXXX        XXXX                        ",
// 	"                        XXXX        XXXXXXXX        XXXX                        ",
// 	"                        XXXX        XXXXXXXX        XXXX                        ",
// 	"                        XXXX        XXXXXXXX        XXXX                        ",
// 	"XXXXXX     XX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XX     XXXXXX",
// 	"XXXXXX     XX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XX     XXXXXX",
// 	"XXXXXX     XX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XX     XXXXXX",
// 	"XXXXXX     XX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XX    XX                                          XX    XX     XXXXXX",
// 	"XXXXXX     XXXXXXXX     XXXX                        XXXX     XXXXXXXX     XXXXXX",
// 	"XXXXXX     XXXXXXXX     XXXX                        XXXX     XXXXXXXX     XXXXXX",
// 	"XXXXXX     XXXXXXXX     XXXX                        XXXX     XXXXXXXX     XXXXXX",
// 	"XXXXXX     XXXXXXXX     XXXX                        XXXX     XXXXXXXX     XXXXXX",
// 	"XXXXXX     XXXXXXXX     XXXX                        XXXX     XXXXXXXX     XXXXXX",
// }

// redRightBottom := []string {
// 	"XXXXXX     XXXXXXXX     XXXX                        XXXX     XXXXXXXX     XXXXXX",
// 	"XXXXXX     XXXXXXXX     XXXX                        XXXX     XXXXXXXX     XXXXXX",
// 	"XXXXXX     XXXXXXXX     XXXX                        XXXX     XXXXXXXX     XXXXXX",
// 	"XXXXXX     XXXXXXXX     XXXX                        XXXX     XXXXXXXX     XXXXXX",
// 	"XXXXXX                  XXXX                        XXXX                  XXXXXX",
// 	"XXXXXX                  XXXX                        XXXX                  XXXXXX",
// 	"XXXXXX                  XXXX                        XXXX                  XXXXXX",
// 	"XXXXXX                  XXXX                        XXXX                  XXXXXX",
// 	"XXXXXX                  XXXX                        XXXX                  XXXXXX",
// 	"XXXXXX                  XXXX                        XXXX                  XXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"XXXXXXXX        XXXX                                        XXXX        XXXXXXXX",
// 	"XXXXXXXX        XXXX                                        XXXX        XXXXXXXX",
// 	"XXXXXXXX        XXXX                                        XXXX        XXXXXXXX",
// 	"XXXXXXXX        XXXX                                        XXXX        XXXXXXXX",
// 	"XXXXXXXX        XXXX                                        XXXX        XXXXXXXX",
// 	"XXXXXXXX        XXXX                                        XXXX        XXXXXXXX",
// 	"XXXXXXXX        XXXX                                        XXXX        XXXXXXXX",
// 	"XXXXXXXX        XXXX                                        XXXX        XXXXXXXX",
// 	"XXXXXXXX        XXXX                                        XXXX        XXXXXXXX",
// 	"XXXXXXXX        XXXX                                        XXXX        XXXXXXXX",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"                XXXX                                        XXXX                ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// redLeftTop:= []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                              XX                XX                              ",
// 	"                              XX                XX                              ",
// 	"                              XX                XX                              ",
// 	"                              XX                XX                              ",
// 	"                              XX                XX                              ",
// 	"                              XX                XX                              ",
// 	"                              XX                XX                              ",
// 	"                              XX                XX                              ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXX    XX                XX    XXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXX    XX                XX    XXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXX    XX                XX    XXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXX    XX                XX    XXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXX    XX                XX    XXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXX    XX                XX    XXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXX    XX                XX    XXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXX            XX    XX    XXXXXXXX    XX    XX            XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX            XX    XX    XXXXXXXX    XX    XX            XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX            XX    XX    XXXXXXXX    XX    XX            XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX            XX    XX    XXXXXXXX    XX    XX            XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX            XX    XX    XXXXXXXX    XX    XX            XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX            XX    XX    XXXXXXXX    XX    XX            XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX            XX    XX    XXXXXXXX    XX    XX            XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX            XX    XX    XXXXXXXX    XX    XX            XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXXXXXXXXXX",
// }

// redLeftBottom := []string {
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXX    XXXXXXXX    XXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX                                                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX                                                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX                                                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX                                                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX                                                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX                                                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX                                                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX                                                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX                                                XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"XXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXX",
// 	"                XXXX    XXXX                        XXXX    XXXX                ",
// 	"                XXXX    XXXX                        XXXX    XXXX                ",
// 	"                XXXX    XXXX                        XXXX    XXXX                ",
// 	"                XXXX    XXXX                        XXXX    XXXX                ",
// 	"                XXXX    XXXX                        XXXX    XXXX                ",
// 	"                XXXX    XXXX                        XXXX    XXXX                ",
// 	"                XXXX    XXXX                        XXXX    XXXX                ",
// 	"                XXXX    XXXX                        XXXX    XXXX                ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// blueTop := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"             XXX        XXXX                        XXXX        XXX             ",
// 	"             XXX        XXXX                        XXXX        XXX             ",
// 	"             XXX        XXXX                        XXXX        XXX             ",
// 	"             XXX        XXXX                        XXXX        XXX             ",
// 	"             XXX        XXXX                        XXXX        XXX             ",
// 	"             XXX        XXXX                        XXXX        XXX             ",
// 	"             XXX        XXXX                        XXXX        XXX             ",
// 	"             XXX        XXXX                        XXXX        XXX             ",
// 	"XXXXX        XXX        XXXXXXXX                XXXXXXXX        XXX        XXXXX",
// 	"XXXXX        XXX        XXXXXXXX                XXXXXXXX        XXX        XXXXX",
// 	"XXXXX        XXX        XXXXXXXX                XXXXXXXX        XXX        XXXXX",
// 	"XXXXX        XXX        XXXXXXXX                XXXXXXXX        XXX        XXXXX",
// 	"XXXXX        XXX        XXXXXXXX                XXXXXXXX        XXX        XXXXX",
// 	"XXXXX        XXX        XXXXXXXX                XXXXXXXX        XXX        XXXXX",
// 	"XXXXX        XXX        XXXXXXXX                XXXXXXXX        XXX        XXXXX",
// 	"XXXXX        XXX        XXXXXXXX                XXXXXXXX        XXX        XXXXX",
// 	"XXXXX        XXX                                                XXX        XXXXX",
// 	"XXXXX        XXX                                                XXX        XXXXX",
// 	"XXXXX        XXX                                                XXX        XXXXX",
// 	"XXXXX        XXX                                                XXX        XXXXX",
// 	"XXXXX        XXX                                                XXX        XXXXX",
// 	"XXXXX        XXX                                                XXX        XXXXX",
// 	"XXXXX        XXX                                                XXX        XXXXX",
// 	"XXXXX        XXX                                                XXX        XXXXX",
// 	"XXXXX        XXX                                                XXX        XXXXX",
// 	"XXXXX        XXX                                                XXX        XXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"              XXXX            XX                XX            XXXX              ",
// 	"              XXXX            XX                XX            XXXX              ",
// 	"              XXXX            XX                XX            XXXX              ",
// 	"              XXXX            XX                XX            XXXX              ",
// 	"              XXXX            XX                XX            XXXX              ",
// 	"              XXXX            XX                XX            XXXX              ",
// 	"              XXXX            XX                XX            XXXX              ",
// 	"              XXXX            XX                XX            XXXX              ",
// 	"XXXXXXXX      XXXX      XXXXXXXX                XXXXXXXX      XXXX      XXXXXXXX",
// 	"XXXXXXXX      XXXX      XXXXXXXX                XXXXXXXX      XXXX      XXXXXXXX",
// }

// blueMiddle := []string{
// 	"XXXXXXXX      XXXX      XXXXXXXX                XXXXXXXX      XXXX      XXXXXXXX",
// 	"XXXXXXXX      XXXX      XXXXXXXX                XXXXXXXX      XXXX      XXXXXXXX",
// 	"              XXXX        XXXXXX                XXXXXX        XXXX              ",
// 	"              XXXX        XXXXXX                XXXXXX        XXXX              ",
// 	"              XXXX        XXXXXX                XXXXXX        XXXX              ",
// 	"              XXXX        XXXXXX                XXXXXX        XXXX              ",
// 	"              XXXX        XXXXXX                XXXXXX        XXXX              ",
// 	"              XXXX        XXXXXX                XXXXXX        XXXX              ",
// 	"              XXXX        XXXXXX                XXXXXX        XXXX              ",
// 	"              XXXX        XXXXXX                XXXXXX        XXXX              ",
// 	"XXXXXXXXXXXXXXXXXXXXXX    XXXXXX                XXXXXX    XXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXX    XXXXXX                XXXXXX    XXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXX    XXXXXX                XXXXXX    XXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXX    XXXXXX                XXXXXX    XXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXX    XXXXXX                XXXXXX    XXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXX    XXXXXX                XXXXXX    XXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXX    XXXXXX                XXXXXX    XXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXX    XXXXXX                XXXXXX    XXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXX    XXXXXX                XXXXXX    XXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXX    XXXXXX                XXXXXX    XXXXXXXXXXXXXXXXXXXXXX",
// 	"                  XXXX    XXXXXX                XXXXXX    XXXX                  ",
// 	"                  XXXX    XXXXXX                XXXXXX    XXXX                  ",
// 	"                  XXXX    XXXXXX                XXXXXX    XXXX                  ",
// 	"                  XXXX    XXXXXX                XXXXXX    XXXX                  ",
// 	"                  XXXX    XXXXXX                XXXXXX    XXXX                  ",
// 	"                  XXXX    XXXXXX                XXXXXX    XXXX                  ",
// 	"                  XXXX    XXXXXX                XXXXXX    XXXX                  ",
// 	"                  XXXX    XXXXXX                XXXXXX    XXXX                  ",
// 	"XXXXXX    XXXX    XXXX    XXXXXX                XXXXXX    XXXX    XXXX    XXXXXX",
// 	"XXXXXX    XXXX    XXXX    XXXXXX                XXXXXX    XXXX    XXXX    XXXXXX",
// 	"XXXXXX    XXXX    XXXX    XXXXXX                XXXXXX    XXXX    XXXX    XXXXXX",
// 	"XXXXXX    XXXX    XXXX    XXXXXX                XXXXXX    XXXX    XXXX    XXXXXX",
// 	"XXXXXX    XXXX    XXXX    XXXXXX                XXXXXX    XXXX    XXXX    XXXXXX",
// 	"XXXXXX    XXXX    XXXX    XXXXXX                XXXXXX    XXXX    XXXX    XXXXXX",
// 	"XXXXXX    XXXX    XXXX    XXXXXX                XXXXXX    XXXX    XXXX    XXXXXX",
// 	"XXXXXX    XXXX    XXXX    XXXXXX                XXXXXX    XXXX    XXXX    XXXXXX",
// 	"XXXXXX    XXXX    XXXX    XXXXXX                XXXXXX    XXXX    XXXX    XXXXXX",
// 	"XXXXXX    XXXX    XXXX    XXXXXX                XXXXXX    XXXX    XXXX    XXXXXX",
// 	"          XXXX    XXXX    XX                        XX    XXXX    XXXX          ",
// 	"          XXXX    XXXX    XX                        XX    XXXX    XXXX          ",
// 	"          XXXX    XXXX    XX                        XX    XXXX    XXXX          ",
// 	"          XXXX    XXXX    XX                        XX    XXXX    XXXX          ",
// 	"          XXXX    XXXX    XX                        XX    XXXX    XXXX          ",
// 	"          XXXX    XXXX    XX                        XX    XXXX    XXXX          ",
// 	"          XXXX    XXXX    XX                        XX    XXXX    XXXX          ",
// 	"          XXXX    XXXX    XX                        XX    XXXX    XXXX          ",
// 	"XXXXXXXXXXXXXX    XXXX    XX                        XX    XXXX    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX    XXXX    XX                        XX    XXXX    XXXXXXXXXXXXXX",
// }

// blueBottom := []string{
// 	"XXXXXXXXXXXXXX    XXXX    XX                        XX    XXXX    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX    XXXX    XX                        XX    XXXX    XXXXXXXXXXXXXX",
// 	"          XXXX    XXXX    XX                        XX    XXXX    XXXX          ",
// 	"          XXXX    XXXX    XX                        XX    XXXX    XXXX          ",
// 	"          XXXX            XX                        XX            XXXX          ",
// 	"          XXXX            XX                        XX            XXXX          ",
// 	"          XXXX            XX                        XX            XXXX          ",
// 	"          XXXX            XX                        XX            XXXX          ",
// 	"          XXXX            XX                        XX            XXXX          ",
// 	"          XXXX            XX                        XX            XXXX          ",
// 	"XXXX      XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXX      XXXX",
// 	"XXXX      XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXX      XXXX",
// 	"XXXX      XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXX      XXXX",
// 	"XXXX      XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXX      XXXX",
// 	"XXXX      XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXX      XXXX",
// 	"XXXX      XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXX      XXXX",
// 	"XXXX      XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXX      XXXX",
// 	"XXXX      XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXX      XXXX",
// 	"XXXX      XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXX      XXXX",
// 	"XXXX      XXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXX      XXXX",
// 	"XXXX                                                                        XXXX",
// 	"XXXX                                                                        XXXX",
// 	"XXXX                                                                        XXXX",
// 	"XXXX                                                                        XXXX",
// 	"XXXX                                                                        XXXX",
// 	"XXXX                                                                        XXXX",
// 	"XXXX                                                                        XXXX",
// 	"XXXX                                                                        XXXX",
// 	"XXXXXXXXXXXXXX                                                    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX                                                    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX                                                    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX                                                    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX                                                    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX                                                    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX                                                    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX                                                    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX                                                    XXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXX                                                    XXXXXXXXXXXXXX",
// 	"          XXXX                                                    XXXX          ",
// 	"          XXXX                                                    XXXX          ",
// 	"          XXXX                                                    XXXX          ",
// 	"          XXXX                                                    XXXX          ",
// 	"          XXXX                                                    XXXX          ",
// 	"          XXXX                                                    XXXX          ",
// 	"          XXXX                                                    XXXX          ",
// 	"          XXXX                                                    XXXX          ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// blueBottomLeft := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXX                            XXXXXXXX                            XXXXXXXX",
// 	"XXXXXXXX                            XXXXXXXX                            XXXXXXXX",
// 	"XXXXXXXX                            XXXXXXXX                            XXXXXXXX",
// 	"XXXXXXXX                            XXXXXXXX                            XXXXXXXX",
// 	"XXXXXXXX                            XXXXXXXX                            XXXXXXXX",
// 	"XXXXXXXX                            XXXXXXXX                            XXXXXXXX",
// 	"XXXXXXXX                            XXXXXXXX                            XXXXXXXX",
// 	"XXXXXXXX                            XXXXXXXX                            XXXXXXXX",
// 	"XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX",
// 	"XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX",
// 	"XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX",
// 	"XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX",
// 	"XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX",
// 	"XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX",
// 	"XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX",
// 	"XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX",
// 	"XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX",
// 	"XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXX    XXXXXXXX",
// 	"            XXXX            XXXX    XXXXXXXX    XXXX            XXXX            ",
// 	"            XXXX            XXXX    XXXXXXXX    XXXX            XXXX            ",
// 	"            XXXX            XXXX    XXXXXXXX    XXXX            XXXX            ",
// 	"            XXXX            XXXX    XXXXXXXX    XXXX            XXXX            ",
// 	"            XXXX            XXXX    XXXXXXXX    XXXX            XXXX            ",
// 	"            XXXX            XXXX    XXXXXXXX    XXXX            XXXX            ",
// 	"            XXXX            XXXX    XXXXXXXX    XXXX            XXXX            ",
// 	"            XXXX            XXXX    XXXXXXXX    XXXX            XXXX            ",
// 	"XXXXXXXXXXXXXXXX    XXXX    XXXX    XXXXXXXX    XXXX    XXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXX    XXXX    XXXXXXXX    XXXX    XXXX    XXXXXXXXXXXXXXXX",
// }

// blueMiddleRight := []string{
// 	"XXXXXXXXXXXXXXXX    XXXX    XXXX    XXXXXXXX    XXXX    XXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXX    XXXX    XXXXXXXX    XXXX    XXXX    XXXXXXXXXXXXXXXX",
// 	"            XXXX    XXXX    XXXX                XXXX    XXXX    XXXX            ",
// 	"            XXXX    XXXX    XXXX                XXXX    XXXX    XXXX            ",
// 	"            XXXX    XXXX    XXXX                XXXX    XXXX    XXXX            ",
// 	"            XXXX    XXXX    XXXX                XXXX    XXXX    XXXX            ",
// 	"            XXXX    XXXX    XXXX                XXXX    XXXX    XXXX            ",
// 	"            XXXX    XXXX    XXXX                XXXX    XXXX    XXXX            ",
// 	"            XXXX    XXXX    XXXX                XXXX    XXXX    XXXX            ",
// 	"            XXXX    XXXX    XXXX                XXXX    XXXX    XXXX            ",
// 	"XXXXXX      XXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXX      XXXXXX",
// 	"XXXXXX      XXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXX      XXXXXX",
// 	"XXXXXX      XXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXX      XXXXXX",
// 	"XXXXXX      XXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXX      XXXXXX",
// 	"XXXXXX      XXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXX      XXXXXX",
// 	"XXXXXX      XXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXX      XXXXXX",
// 	"XXXXXX      XXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXX      XXXXXX",
// 	"XXXXXX      XXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXX      XXXXXX",
// 	"XXXXXX      XXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXX      XXXXXX",
// 	"XXXXXX      XXXX    XXXX    XXXXXXXXXXXXXXXXXXXXXXXX    XXXX    XXXX      XXXXXX",
// 	"            XXXX    XXXX                                XXXX    XXXX            ",
// 	"            XXXX    XXXX                                XXXX    XXXX            ",
// 	"            XXXX    XXXX                                XXXX    XXXX            ",
// 	"            XXXX    XXXX                                XXXX    XXXX            ",
// 	"            XXXX    XXXX                                XXXX    XXXX            ",
// 	"            XXXX    XXXX                                XXXX    XXXX            ",
// 	"            XXXX    XXXX                                XXXX    XXXX            ",
// 	"            XXXX    XXXX                                XXXX    XXXX            ",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// orangeRightBottom := []string{
// 	"XXXX    XXXX    XXXX    XXXX        XXXXXXXX        XXXX    XXXX    XXXX    XXXX",
// 	"XXXX    XXXX    XXXX    XXXX        XXXXXXXX        XXXX    XXXX    XXXX    XXXX",
// 	"        XXXX            XXXX        XXXXXXXX        XXXX            XXXX        ",
// 	"        XXXX            XXXX        XXXXXXXX        XXXX            XXXX        ",
// 	"        XXXX            XXXX        XXXXXXXX        XXXX            XXXX        ",
// 	"        XXXX            XXXX        XXXXXXXX        XXXX            XXXX        ",
// 	"        XXXX            XXXX        XXXXXXXX        XXXX            XXXX        ",
// 	"        XXXX            XXXX        XXXXXXXX        XXXX            XXXX        ",
// 	"        XXXX            XXXX        XXXXXXXX        XXXX            XXXX        ",
// 	"        XXXX            XXXX        XXXXXXXX        XXXX            XXXX        ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// }

// orangeRightTop := []string{
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                    XXXX                                    XXXX",
// 	"                                    XXXX                                    XXXX",
// 	"                                    XXXX                                    XXXX",
// 	"                                    XXXX                                    XXXX",
// 	"                                    XXXX                                    XXXX",
// 	"                                    XXXX                                    XXXX",
// 	"                                    XXXX                                    XXXX",
// 	"                                    XXXX                                    XXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX",
// 	"                            XXXX                                    XXXX        ",
// 	"                            XXXX                                    XXXX        ",
// 	"                            XXXX                                    XXXX        ",
// 	"                            XXXX                                    XXXX        ",
// 	"                            XXXX                                    XXXX        ",
// 	"                            XXXX                                    XXXX        ",
// 	"                            XXXX                                    XXXX        ",
// 	"                            XXXX                                    XXXX        ",
// 	"XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          XXXXXXXXXXXXXXXXXXXX",
// 	"                XXXX                XXXX                    XXXX            XXXX",
// 	"                XXXX                XXXX                    XXXX            XXXX",
// 	"                XXXX                XXXX                    XXXX            XXXX",
// 	"                XXXX                XXXX                    XXXX            XXXX",
// 	"                XXXX                XXXX                    XXXX            XXXX",
// 	"                XXXX                XXXX                    XXXX            XXXX",
// 	"                XXXX                XXXX                    XXXX            XXXX",
// 	"                XXXX                XXXX                    XXXX            XXXX",
// 	"XXXX    XXXX    XXXX    XXXX        XXXXXXXX        XXXX    XXXX    XXXX    XXXX",
// 	"XXXX    XXXX    XXXX    XXXX        XXXXXXXX        XXXX    XXXX    XXXX    XXXX",
// }

// orangeLeftTop := []string{
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"                    XXXX                                XXXX                    ",
// 	"                    XXXX                                XXXX                    ",
// 	"                    XXXX                                XXXX                    ",
// 	"                    XXXX                                XXXX                    ",
// 	"                    XXXX                                XXXX                    ",
// 	"                    XXXX                                XXXX                    ",
// 	"                    XXXX                                XXXX                    ",
// 	"                    XXXX                                XXXX                    ",
// 	"XXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXXXXXXXXXX                                XXXXXXXXXXXXXXXXXXXXXXXX",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"                                                                                ",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX",
// 	"            XXXX                                                XXXX            ",
// 	"            XXXX                                                XXXX            ",
// 	"            XXXX                                                XXXX            ",
// 	"            XXXX                                                XXXX            ",
// 	"            XXXX                                                XXXX            ",
// 	"            XXXX                                                XXXX            ",
// 	"            XXXX                                                XXXX            ",
// 	"            XXXX                                                XXXX            ",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// }

// orangeLeftBottom := []string{
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXX                                    XXXX                                    ",
// 	"XXXX                                    XXXX                                    ",
// 	"XXXX                                    XXXX                                    ",
// 	"XXXX                                    XXXX                                    ",
// 	"XXXX                                    XXXX                                    ",
// 	"XXXX                                    XXXX                                    ",
// 	"XXXX                                    XXXX                                    ",
// 	"XXXX                                    XXXX                                    ",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"XXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
// 	"            XXXX                                    XXXX                        ",
// 	"            XXXX                                    XXXX                        ",
// 	"            XXXX                                    XXXX                        ",
// 	"            XXXX                                    XXXX                        ",
// 	"            XXXX                                    XXXX                        ",
// 	"            XXXX                                    XXXX                        ",
// 	"            XXXX                                    XXXX                        ",
// 	"            XXXX                                    XXXX                        ",
// 	"XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXX",
// 	"XXXX                    XXXX            XXXX                    XXXX            ",
// 	"XXXX                    XXXX            XXXX                    XXXX            ",
// 	"XXXX                    XXXX            XXXX                    XXXX            ",
// 	"XXXX                    XXXX            XXXX                    XXXX            ",
// 	"XXXX                    XXXX            XXXX                    XXXX            ",
// 	"XXXX                    XXXX            XXXX                    XXXX            ",
// 	"XXXX                    XXXX            XXXX                    XXXX            ",
// 	"XXXX                    XXXX            XXXX                    XXXX            ",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// 	"XXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXX",
// }
